---
name: "Release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release to GitHub"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false